<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="57.865" tests="2" failures="1">
  <testsuite name="Root Suite" timestamp="2020-04-15T20:39:02" tests="0" file="cypress/integration/apps/lims/LM23.js" failures="0" time="0">
  </testsuite>
  <testsuite name="23 - I should be able to fail samples" timestamp="2020-04-15T20:39:02" tests="2" failures="1" time="57.865">
    <testcase name="23 - I should be able to fail samples LM-23-1 Should be able to fail a sample row" time="34.731" classname="LM-23-1 Should be able to fail a sample row">
    </testcase>
    <testcase name="23 - I should be able to fail samples LM-23-2 Should not fail samples that are completed" time="11.567" classname="LM-23-2 Should not fail samples that are completed">
    </testcase>
    <testcase name="23 - I should be able to fail samples &quot;after all&quot; hook for &quot;LM-23-2 Should not fail samples that are completed&quot;" time="11.567" classname="&quot;after all&quot; hook for &quot;LM-23-2 Should not fail samples that are completed&quot;">
      <failure message="cy.exec(&apos;esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/lims/LM23teardown.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line 11, in &lt;module&gt;
    load_entry_point(&apos;espclient&apos;, &apos;console_scripts&apos;, &apos;esp&apos;)()
  File &quot;/Users/cj/bi...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;23 - I should be able to fa...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp -s -P 443 -H chris.test.l7informatics.com -u admin@localhost -p L4b7R0cks! seed -f -d cypress/fixtures/apps/lims/LM23teardown.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line 11, in <module>
    load_entry_point('espclient', 'console_scripts', 'esp')()
  File "/Users/cj/bi...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '23 - I should be able to fa...'
    at cypressErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:138017:3)
    at https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (https://chris.test.l7informatics.com/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>