<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="23.733" tests="1" failures="2">
  <testsuite name="Root Suite" timestamp="2020-03-28T19:49:36" tests="0" file="cypress/integration/apps/lims/LM39.js" failures="0" time="0">
  </testsuite>
  <testsuite name="39 - I can read protocol step descriptions in the inspector" timestamp="2020-03-28T19:49:36" tests="1" failures="2" time="23.733">
    <testcase name="39 - I can read protocol step descriptions in the inspector LM-39-1 Should view protocol details" time="0" classname="LM-39-1 Should view protocol details">
      <failure message="Timed out retrying: Expected to find content: &apos;First line&apos; within the element: &lt;article.protocol-sop-information&gt; but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'First line' within the element: <article.protocol-sop-information> but never did.
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at retry (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="39 - I can read protocol step descriptions in the inspector &quot;after all&quot; hook for &quot;LM-39-1 Should view protocol details&quot;" time="23.733" classname="&quot;after all&quot; hook for &quot;LM-39-1 Should view protocol details&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM39seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 14:50:02,063:Saving data in Experiment LM39 for Protocol: Barcode Protocol.
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line 1...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;39 - I can read protocol st...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM39seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 14:50:02,063:Saving data in Experiment LM39 for Protocol: Barcode Protocol.
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line 1...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '39 - I can read protocol st...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>