<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="6" failures="2">
  <testsuite name="Root Suite" timestamp="2020-03-28T16:53:43" tests="0" file="cypress/integration/apps/entities/EN25_2.js" failures="0" time="0">
  </testsuite>
  <testsuite name="25 - I can see correct processed data in entity details" timestamp="2020-03-28T16:53:43" tests="6" failures="2" time="0">
    <testcase name="25 - I can see correct processed data in entity details &quot;before all&quot; hook for &quot;EN-25-7 Should find location column&quot;" time="0" classname="&quot;before all&quot; hook for &quot;EN-25-7 Should find location column&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed --no-overwrite cypress/fixtures/apps/entities/EN25_2seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 11:53:45,330:Creating Container: EN25 sample single
INFO:root:2020-03-28 11:53:45,565:Creating Item: EN2511 item
INFO:root:2020-03-28 11:53:45,763:Creating Protocol: EN25-7 sta...

Because this error occurred during a &apos;before all&apos; hook we are skipping the remaining tests in the current suite: &apos;25 - I can see correct proc...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed --no-overwrite cypress/fixtures/apps/entities/EN25_2seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 11:53:45,330:Creating Container: EN25 sample single
INFO:root:2020-03-28 11:53:45,565:Creating Item: EN2511 item
INFO:root:2020-03-28 11:53:45,763:Creating Protocol: EN25-7 sta...

Because this error occurred during a 'before all' hook we are skipping the remaining tests in the current suite: '25 - I can see correct proc...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="25 - I can see correct processed data in entity details &quot;after all&quot; hook for &quot;EN-25-7 Should find location column&quot;" time="0" classname="&quot;after all&quot; hook for &quot;EN-25-7 Should find location column&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/entities/EN25_2seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 11:53:53,489:Saving data in Experiment EN25-8 for Protocol: EN25-8 standard.
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line ...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;25 - I can see correct proc...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/entities/EN25_2seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 11:53:53,489:Saving data in Experiment EN25-8 for Protocol: EN25-8 standard.
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line ...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '25 - I can see correct proc...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>