<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="34.899" tests="6" failures="3" skipped="2">
  <testsuite name="Root Suite" timestamp="2020-03-22T19:58:49" tests="0" file="cypress/integration/apps/permissions/LP24.js" failures="0" time="0">
  </testsuite>
  <testsuite name="24 - I can have experiment permissions" timestamp="2020-03-22T19:58:49" tests="6" failures="3" time="34.899">
    <testcase name="24 - I can have experiment permissions LP-24-4 Should fail to create an experiment" time="34.899" classname="LP-24-4 Should fail to create an experiment">
    </testcase>
    <testcase name="24 - I can have experiment permissions LP-24-5 Should fail to update an experiment" time="0" classname="LP-24-5 Should fail to update an experiment">
      <failure message="Timed out retrying: Expected to find content: &apos;LP24 no update&apos; within the selector: &apos;.section .row a&apos; but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'LP24 no update' within the selector: '.section .row a' but never did.
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at retry (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="24 - I can have experiment permissions LP-24-1 Should create an experiment" time="0" classname="LP-24-1 Should create an experiment">
      <failure message="Timed out retrying: Expected to find content: &apos;LP24 create&apos; within the selector: &apos;.body .row&apos; but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'LP24 create' within the selector: '.body .row' but never did.
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at retry (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
    <testcase name="24 - I can have experiment permissions LP-24-2 Should update an experiment" time="0" classname="LP-24-2 Should update an experiment">
      <failure message="Timed out retrying: Expected to find content: &apos;LP24 update&apos; within the selector: &apos;.section .row a&apos; but never did." type="CypressError"><![CDATA[CypressError: Timed out retrying: Expected to find content: 'LP24 update' within the selector: '.section .row a' but never did.
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at retry (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:132299:19)
    at onFailFn (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:120514:16)
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163008:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>