<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="24.136" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-03-28T20:09:38" tests="0" file="cypress/integration/apps/lims/LM57.js" failures="0" time="0">
  </testsuite>
  <testsuite name="57 - I can use LIMS link in the nav bar" timestamp="2020-03-28T20:09:38" tests="1" failures="1" time="24.136">
    <testcase name="57 - I can use LIMS link in the nav bar LM-57-1 Should use LIMS link" time="12.068" classname="LM-57-1 Should use LIMS link">
    </testcase>
    <testcase name="57 - I can use LIMS link in the nav bar &quot;after all&quot; hook for &quot;LM-57-1 Should use LIMS link&quot;" time="12.068" classname="&quot;after all&quot; hook for &quot;LM-57-1 Should use LIMS link&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM57seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 15:09:52,719:Saving data in Experiment LM57 for Protocol: LM57 Standard.
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line 11, ...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;57 - I can use LIMS link in...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM57seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 15:09:52,719:Saving data in Experiment LM57 for Protocol: LM57 Standard.
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line 11, ...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '57 - I can use LIMS link in...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>