<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="31.098" tests="3" failures="1">
  <testsuite name="Root Suite" timestamp="2020-03-28T19:31:47" tests="0" file="cypress/integration/apps/lims/LM24.js" failures="0" time="0">
  </testsuite>
  <testsuite name="24 - I should be able to run sample protocols with all options" timestamp="2020-03-28T19:31:47" tests="3" failures="1" time="31.098">
    <testcase name="24 - I should be able to run sample protocols with all options LM-24-1 Should be able to run Sample Protocol with 1:1 relation" time="19.458" classname="LM-24-1 Should be able to run Sample Protocol with 1:1 relation">
    </testcase>
    <testcase name="24 - I should be able to run sample protocols with all options LM-24-2 Should be able to run Sample Protocol with 1:N relation" time="5.1" classname="LM-24-2 Should be able to run Sample Protocol with 1:N relation">
    </testcase>
    <testcase name="24 - I should be able to run sample protocols with all options LM-24-3 Should be able to run Sample Protocol with N:1 relation" time="3.27" classname="LM-24-3 Should be able to run Sample Protocol with N:1 relation">
    </testcase>
    <testcase name="24 - I should be able to run sample protocols with all options &quot;after all&quot; hook for &quot;LM-24-3 Should be able to run Sample Protocol with N:1 relation&quot;" time="3.27" classname="&quot;after all&quot; hook for &quot;LM-24-3 Should be able to run Sample Protocol with N:1 relation&quot;">
      <failure message="cy.exec(&apos;esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM24seed.yml&apos;) failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 14:32:17,132:Saving data in Experiment LM24-1 for Protocol: Standard 1to1.
Traceback (most recent call last):
  File &quot;/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp&quot;, line 11...

Because this error occurred during a &apos;after all&apos; hook we are skipping the remaining tests in the current suite: &apos;24 - I should be able to ru...&apos;" type="CypressError"><![CDATA[CypressError: cy.exec('esp  -P 8080 -H 127.0.0.1 -u admin@localhost -p admin seed -f -d cypress/fixtures/apps/lims/LM24seed.yml') failed because the command exited with a non-zero code.

Pass {failOnNonZeroExit: false} to ignore exit code failures.

Information about the failure:
Code: 1

Stderr:
INFO:root:2020-03-28 14:32:17,132:Saving data in Experiment LM24-1 for Protocol: Standard 1to1.
Traceback (most recent call last):
  File "/Users/cj/bitrepos/esp/develop/bin/.venv/bin/esp", line 11...

Because this error occurred during a 'after all' hook we are skipping the remaining tests in the current suite: '24 - I should be able to ru...'
    at cypressErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138036:9)
    at throwErr (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:137969:11)
    at Object.throwErrByPath (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:138017:3)
    at http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:125593:26
    at tryCatcher (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:164895:23)
    at Promise._settlePromiseFromHandler (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162831:31)
    at Promise._settlePromise (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162888:18)
    at Promise._settlePromise0 (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:162933:10)
    at Promise._settlePromises (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:163012:18)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159620:16)
    at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159630:10)
    at Async.drainQueues (http://127.0.0.1:8080/__cypress/runner/cypress_runner.js:159504:14)]]></failure>
    </testcase>
  </testsuite>
</testsuites>